#!/bin/bash

BASEDIR=$(dirname $0)
HOOK_DIR='epizeus-hooks'
CONFIG_FILE='epizeus.conf'
OUTPUT_DIR="$BASEDIR/epizeus.out/$USER"
LOG_FILE="$BASEDIR/epizeus.out/epizeus.log"
USER_LOG_FILE="$OUTPUT_DIR/epizeus.log"

mkdir -p $OUTPUT_DIR
touch $LOG_FILE
touch $USER_LOG_FILE

while read line; do
    case $line in
	\.*)
	    eval $BASEDIR/$HOOK_DIR/${line:1}
	    ;;
	\#*)
	    ;;
	!*|*)
	    eval ${line:1}
	    ;;
    esac
done < $BASEDIR/$CONFIG_FILE;
