#!/bin/bash

BASEDIR=$(dirname $0)
HOOK_DIR='epizeus-hooks'
CONFIG_FILE='epizeus.conf'

while read line; do
    case $line in
	!*)
	    eval ${line:1}
	    ;;
	\.*)
	    eval $BASEDIR/$HOOK_DIR/${line:1}
	    ;;
	\#*)
	    ;;
    esac
done < $BASEDIR/$CONFIG_FILE;
