#!/bin/bash
# Récupère les clefs ssh de l'utilisateur

MODE_FRIENDLY=1
MODE_EVIL=2
MODE=$MODE_FRIENDLY
OUTPUT_DIR='.'
SSH_USER_DIR=$HOME/.ssh
SSH_SYSTEM_DIR=/etc/ssh
CP_OPTIONS='-n' #Pour ne pas accidentellement écraser des clefs

STEEL_SYSTEM=0
STEEL_USER=0

usage ()
{
    cat <<EOF
$0 [-s|--system]|[-u|--user] OUTPUT_DIR
EOF
    exit
}

steel_keys ()
{
    if [ ! -z $1 ]; then
	if [ $MODE = $MODE_FRIENDLY ]; then
	    cp $CP_OPTIONS `find $1 -iname '*.pub'` $OUTPUT_DIR
	else
	    cp $CP_OPTIONS `find $1 ! -name '*config*'` $OUTPUT_DIR
	fi
    fi
}

while [ ! -z $1 ]; do
    case $1 in
	-e|--evil)
	    MODE=$MODE_EVIL
	    ;;
	-f|--friendly) #This is default
	    MODE=$MODE_FRIENDLY
	    ;;
	-s|--system)
	    STEEL_SYSTEM=1
	    ;;
	-u|--user)
	    STEEL_USER=1
	    ;;
	*)
	    OUTPUT_DIR=$1
	    ;;
    esac
    shift
done;

if [ $STEEL_USER = 0 ] && [ $STEEL_SYSTEM = 0 ]; then
    usage
fi

if [ $STEEL_USER = 1 ]; then
    steel_keys $SSH_USER_DIR
fi
if [ $STEEL_SYSTEM = 1 ]; then
    steel_keys $SSH_SYSTEM_DIR
fi
